version: "3.7"

services: 

    flask:
        build: ./flask
        container_name: flask1
        restart: always
        environment: 
            - APP_NAME=MyFlaskApp
            - DB_USERNAME=example
        expose: 
            - 5000

    
    nginx:
        build: ./nginx
        container_name: nginx1
        restart: always
        ports: 
            - "80:80"